### ISSUE TITLE
When Parsing a Bundle, ReadLiteralToken() during ReadAddress returns the whole payload

### ISSUE THREAD

**Issue by theladyjaye** [tilde-love/osc-core#1]
So, for example:

```
"#bundle\0????B^ff\0\0\0(/foo/bar4/baz1234\0\0\0"
```

`ReadNextToken` in `OscStringReader` comes back with a Literal token which is the whole value above. That will than fail when it attempts to verify the ident in `OscBundle.BundleIdent`:

```
public new static OscBundle Parse(ref OscStringReader reader, IFormatProvider provider = null, OscSerializationToken endToken = OscSerializationToken.End)
        {
            if (provider == null)
            {
                provider = CultureInfo.InvariantCulture;
            }

            string ident = reader.ReadAddress(false)
                .Trim();

            if (BundleIdent.Equals(ident, StringComparison.Ordinal) == false) // <---- This equality check fails
            {
                throw new Exception($"Invalid bundle ident '{ident}'");
            }
…
```

**Comment by theladyjaye** [comment]
Ah, nevermind. I guess we are supposed to use `OscPacket/OscBundle.Read(byte[] index, count)`

My Bad!

**Comment by philltew** [comment]
That is correct, Read / Write are for binary.
 OscStringReader will read correctly formatted human readable strings. 

For example the bundle in the OP could be parsed from a string like this. 
`#bundle, 23-08-2013 01:00:34.3530Z, { /foo/bar4/baz1234 }`

The parsing is the same format (pretty much) as Rug.Osc.
See the Rug.Osc wiki for a full guide [Parsing messages and bundles from strings](https://bitbucket.org/rugcode/rug.osc/wiki/Parsing%20messages%20and%20bundles%20from%20strings)
