### ISSUE TITLE
Example for sending and receiving messsages?

### ISSUE THREAD

**Issue by pixtur** [tilde-love/osc-core#4]
Hi. This library looks great! 
Is there some introduction material on how to get started, e.g. like send receiving simple messages over UDP?

kind regards,
tom

**Comment by philltew** [comment]
Thank you Tom, 

Jon Skeet has a [simple sender receiver demo](https://github.com/jskeet/DemoCode/tree/main/OscMixerControl) and accompanying [blog post](https://codeblog.jonskeet.uk/2021/01/27/osc-mixer-control-in-c/)

There is currently no material of that sort as part of OscCore, the purpose of OscCore is to be a performant OSC format library while being transport layer agnostic. 

[Rug.Osc](https://bitbucket.org/rugcode/rug.osc/src/master/) has lots of this sort of thing, is very easy to get up and running with and is perfectly good for most use cases.

**Comment by philltew** [comment]
I'm closing this issue as I can see you have decided to use Rug.Osc in your project.

**Comment by pixtur** [comment]
Hi. Thanks again. Indeed Rug.Osc does a very good job so far.
